export const PROMPT_TITLES = [
  "Write a prompt to create an AI assistant that acts like a senior web developer",
  "Write a prompt to generate the HTML and CSS for a modern portfolio website",
  "Write a prompt to design a custom AI agent that helps students learn math",
  "Write a prompt to build a responsive landing page for a new coffee shop",
  "Write a prompt to create an AI chatbot that schedules appointments for a clinic",
  "Write a prompt to generate a React component for a dark-mode navigation bar",
  "Write a prompt to instruct an AI to write a Python script for scraping weather data",
  "Write a prompt to build a simple e-commerce shopping cart using JavaScript",
  "Write a prompt to create an AI agent that summarizes long PDF documents",
  "Write a prompt to generate a landing page for a fitness app",
  "Write a prompt to build an AI tutor that explains complex physics concepts to a 10-year-old",
  "Write a prompt to create a blog layout using CSS Grid",
  "Write a prompt to design an AI agent that acts as a language translation assistant",
  "Write a prompt to build a contact form with validation in HTML and JS",
  "Write a prompt to instruct an AI to write a Python automation script for organizing downloads",
  "Write a prompt to create a pricing table for a SaaS website",
  "Write a prompt to design an AI virtual assistant that helps users plan a 5-day vacation",
  "Write a prompt to build a modern footer for a corporate website",
  "Write a prompt to create an AI that can generate weekly meal plans based on dietary restrictions",
  "Write a prompt to build a responsive image gallery using CSS Flexbox",
  "Write a prompt to instruct an AI to write an SQL query to find top-selling products",
  "Write a prompt to create a custom 404 error page for a web application",
  "Write a prompt to design an AI agent that evaluates resumes for a tech job",
  "Write a prompt to build a hero section with a video background in HTML/CSS",
  "Write a prompt to create an AI chatbot that provides customer support for a clothing brand",
  "Write a prompt to generate a login and registration page using Tailwind CSS",
  "Write a prompt to instruct an AI to write a script for fetching data from a public API",
  "Write a prompt to build an 'About Us' page for a digital marketing agency",
  "Write a prompt to create an AI that acts as a coding mentor to debug JavaScript errors",
  "Write a prompt to generate a responsive sidebar navigation menu",
  "Write a prompt to design an AI agent that tracks daily expenses and categorizes them",
  "Write a prompt to build a testimonials slider component for a website",
  "Write a prompt to instruct an AI to write a basic Node.js Express server",
  "Write a prompt to create a product detail page for an online store",
  "Write a prompt to build an AI agent that generates ideas for YouTube videos",
  "Write a prompt to design a minimalist 'Coming Soon' page",
  "Write a prompt to create an AI that helps users learn a new programming language step-by-step",
  "Write a prompt to build a multi-step form wizard in React",
  "Write a prompt to instruct an AI to write a regex to validate email addresses",
  "Write a prompt to create a newsletter signup section for a blog",
  "Write a prompt to design an AI assistant that acts as a financial advisor",
  "Write a prompt to build a dashboard layout with charts and widgets",
  "Write a prompt to create an AI agent that generates social media captions for Instagram",
  "Write a prompt to generate a CSS animation for a loading spinner",
  "Write a prompt to instruct an AI to write a unit test for a simple calculator function",
  "Write a prompt to build an FAQ section with an accordion style",
  "Write a prompt to create an AI chatbot that recommends books based on user preferences",
  "Write a prompt to generate an HTML email template for a marketing campaign",
  "Write a prompt to design an AI agent that helps writers overcome writer's block",
  "Write a prompt to build a sticky header that changes color on scroll",
  "Write a prompt to instruct an AI to write a Python script that resizes images",
  "Write a prompt to create a feature comparison table for a software product",
  "Write a prompt to design an AI virtual therapist that provides basic mental health exercises",
  "Write a prompt to build a modern card component with hover effects",
  "Write a prompt to create an AI agent that helps users practice interview questions",
  "Write a prompt to generate a parallax scrolling effect for a website",
  "Write a prompt to instruct an AI to write a MongoDB aggregation query",
  "Write a prompt to build a 'Meet the Team' section with profile pictures",
  "Write a prompt to create an AI that acts as a personal fitness trainer",
  "Write a prompt to design a responsive HTML table for displaying tabular data",
  "Write a prompt to build an AI agent that generates SEO-optimized blog posts",
  "Write a prompt to generate a toggle switch for light/dark mode",
  "Write a prompt to instruct an AI to write a bash script for backing up a folder",
  "Write a prompt to create a pagination component for a list of articles",
  "Write a prompt to design an AI assistant that acts as a sommelier to recommend wines",
  "Write a prompt to build a breadcrumb navigation trail",
  "Write a prompt to create an AI agent that summarizes the latest tech news",
  "Write a prompt to generate a masonry layout for an image portfolio",
  "Write a prompt to instruct an AI to write a simple smart contract in Solidity",
  "Write a prompt to build a timeline component to show company history",
  "Write a prompt to create an AI chatbot that helps users learn basic Spanish",
  "Write a prompt to design a progress bar that animates on page load",
  "Write a prompt to build an AI agent that helps users negotiate a salary offer",
  "Write a prompt to generate a modal popup window in CSS and JS",
  "Write a prompt to instruct an AI to write a web scraper using Cheerio or BeautifulSoup",
  "Write a prompt to create a search bar with a dropdown of autocomplete suggestions",
  "Write a prompt to design an AI that acts as a personal stylist for clothing recommendations",
  "Write a prompt to build a tooltip component that appears on hover",
  "Write a prompt to create an AI agent that plans a weekly workout routine",
  "Write a prompt to generate a floating action button (FAB) for a mobile-first web app",
  "Write a prompt to instruct an AI to write a cron job for running tasks automatically",
  "Write a prompt to build a rating component with clickable stars",
  "Write a prompt to create an AI that helps users discover new music based on their mood",
  "Write a prompt to design a user profile page layout with a cover image",
  "Write a prompt to build an AI agent that acts as a mock investor for pitching a startup",
  "Write a prompt to generate a sticky 'Back to Top' button",
  "Write a prompt to instruct an AI to write a Python function that reverses a string",
  "Write a prompt to create an event schedule layout with times and speakers",
  "Write a prompt to design an AI assistant that helps users track their carbon footprint",
  "Write a prompt to build a dropzone component for file uploads",
  "Write a prompt to create an AI agent that generates creative writing prompts",
  "Write a prompt to generate an off-canvas menu for mobile navigation",
  "Write a prompt to instruct an AI to write a SQL query to join three tables",
  "Write a prompt to build a pricing calculator component based on user input",
  "Write a prompt to create an AI that acts as a travel guide for a specific city",
  "Write a prompt to design a video player interface with custom controls",
  "Write a prompt to build an AI agent that helps users learn how to play chess",
  "Write a prompt to generate a split-screen layout for a login page",
  "Write a prompt to instruct an AI to write a React hook for fetching data",
  "Write a prompt to create a toast notification system for displaying alerts"
];
